const { defineModel } = require("../repository");

module.exports = defineModel({
  table: "players",
  idPrefix: "p",
  defaults: {
    lastName: "",
    nationality: "Nepal",
    countryOfBirth: "Nepal",
    preferredFoot: "Right",
    squad: "First Team",
    status: "Active",
    contractStatus: "Active",
  },
  columns: [
    { field: "photo", column: "photo", type: "string" },
    { field: "firstName", column: "first_name", type: "string" },
    { field: "lastName", column: "last_name", type: "string" },
    { field: "displayName", column: "display_name", type: "string" },
    { field: "name", column: "name", type: "string" },
    { field: "dob", column: "dob", type: "string" },
    { field: "nationality", column: "nationality", type: "string" },
    { field: "countryOfBirth", column: "country_of_birth", type: "string" },
    { field: "height", column: "height", type: "number" },
    { field: "weight", column: "weight", type: "number" },
    { field: "preferredFoot", column: "preferred_foot", type: "string" },
    { field: "position", column: "position", type: "string" },
    { field: "secondaryPosition", column: "secondary_position", type: "string" },
    { field: "jersey", column: "jersey", type: "number" },
    { field: "teamId", column: "team_id", type: "string", fk: true },
    { field: "squad", column: "squad", type: "string" },
    { field: "status", column: "status", type: "string" },
    { field: "dateJoined", column: "date_joined", type: "string" },
    { field: "contractStart", column: "contract_start", type: "string" },
    { field: "contractEnd", column: "contract_end", type: "string" },
    { field: "contractStatus", column: "contract_status", type: "string" },
  ],
});
